name: '532-group'
channels:
  - conda-forge
  - defaults
dependencies:
  - ipykernel=6.22.0
  - altair-all=5.5.0
  - dash=2.9.3
  - dash-bootstrap-components=1.6.0
  - plotly=5.15.0
  - tabulate=0.9.0
  - lxml=4.9.2
  - pyarrow=12.0.*
  - numpy<2.0
  - pip
  - pip:
      - dash-vega-components==0.11.0